### ISSUE TITLE
Any reason to use a string key instead of a generic K?

### ISSUE THREAD

**Issue by TennyZhuang** [ihciah/singleflight-async#1]
The commit https://github.com/TennyZhuang/singleflight-async/commit/10776c00cfd522dfc742c5f5a9e6a6d0b844fd74 reduced 50 loc, remove an unnecessary API and can be used in more general scenes. Are there some specific reasons that only support the string key?

If you think the API is better, I can submit a PR here.

**Comment by ihciah** [comment]
Sorry I didn't noticed this issue for so long time.
Make key generic sounds good! Do you have any idea to make this change compatible(I changed some design yesterday) with old versions? Users can pass &str now, which may have to be converted to owned type to extend lifetime.
Maybe K: `Hash + Eq + ToOwned`?

**Comment by TennyZhuang** [comment]
Converting a concrete type argument to a generic one is always a break change, since callers can always initiate the struct without do anything. Then before the change, the code compiles with only warnings, but fail to compile after the change due to type inference error. But in most cases, the caller only needs to change few codes to migrate. So how about just releasing 0.2.0?

**Comment by TennyZhuang** [comment]
BTW I can rework based on your yesterday’s change if the idea is acceptable.

**Comment by ihciah** [comment]
> Converting a concrete type argument to a generic one is always a break change

I get it. I only considered the already inferenced type before. I agree we should publish 0.2.0, then it seems no need for considering compatibility.

> BTW I can rework based on your yesterday’s change if the idea is acceptable.

Thank you very much! Please work based on the newest changes. The former code didn't considered the cases when the main task is dropped before ready, which may cause all waiters waiting infinitly. The newest change fixed this issue and removed all unsafe code(maybe you can add `#![forbid(unsafe_code)]` by the way).

I also invited you as the owner of this repo and crates-io. If you are willing to maintain this repo we can work together.

**Comment by ihciah** [comment]
Close due to feature is implemented and merged.
